session13/project/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.home, name="home"),
]

session13/project/blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns =[
    path('', views.home, name="home"),
    path('new/', views.new, name="new"),
    path('detail/<int:post_pk>/', views.detail,	name="detail"),
    path('edit/<int:post_pk>/', views.edit,	name="edit"),
    path('delete/<int:post_pk>/', views.delete,	name="delete"),
    path('delete-comment/<int:post_pk>/<int:comment_pk>', views.delete_comment, name='delete_comment'),
    path("registration/signup/", views.signup, name="signup"),
    path("registration/login/", views.login, name="login"),
    path("registration/logout/", views.logout, name="logout"),
]

session13/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

session13/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(help_text="User Age", blank=True, null=True)

    class Meta:
        verbose_name = "User_Profile"
        verbose_name_plural = "User_Profiles"

    def __str__(self):
        return f'{self.pk}. {self.user}'

session13/project/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title	= models.CharField(verbose_name='TITLE', max_length=50)
    content	= models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    author	= models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_posts", null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_dt', 'author')

    def __str__(self):
        return f'{self.title}입니다'
    def get_absolute_url(self):
        return reverse(f'blog:post_detail', args=[self.id])
    def get_previous(self):
        return self.get_previous_by_create_dt()
    def get_next(self):
        return self.get_next_by_create_dt()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name ='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name ='my_comments')
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_dt', 'post', 'author')

    def __str__(self):
        return f'{self.author}-{self.content}'

session13/project/accounts/views.py
from django.shortcuts import render

def home(request):
    return render(request,'accounts/home.html')

# Create your views here.

session13/project/blog/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from .models import Comment, Post

def signup(request):
   if request.method == 'POST':
       username = request.POST['username']
       password = request.POST['password']
            
       exist_user = User.objects.filter(username=username)

       if exist_user:
            error = "이미 존재하는 유저입니다."
            return render(request, 'blog/registration/signup.html', {"error":error})

       new_user = User.objects.create_user(username=username, password=password)
       auth.login(request, new_user)
       return redirect('blog:home')

   return render(request, 'blog/registration/signup.html')

def login(request):
   if request.method == 'POST':
       username = request.POST['username']
       password = request.POST['password']

       user = auth.authenticate(username=username, password=password)

       if user is not None:
            auth.login(request, user)
            return redirect('blog:home')
       error = "아이디 또는 비밀번호가 틀립니다"
       return render(request, 'blog/registration/login.html', {"error":error})

   return render(request, 'blog/registration/login.html')

def home(request):
   posts = Post.objects.all()

   return render(request, 'blog/home.html', {'posts':posts})

def logout(request):
   auth.logout(request)
   return redirect('blog:home')

@login_required(login_url="/blog/registration/login/")
def new(request):
   if request.method == "POST":
       title = request.POST['title']
       content = request.POST['content']


       new_post = Post.objects.create(
           title=title,
           content=content,
           author=request.user)
       return redirect('blog:detail', new_post.pk)
  
   return render(request, 'blog/new.html')

@login_required(login_url="/blog/registration/login/")
def detail(request, post_pk):
   post = Post.objects.get(pk=post_pk)
   
   if request.method == 'POST':
        content = request.POST['content']
        Comment.objects.create(
            post=post,
            content=content,
            author=request.user
        )
        return redirect('blog:detail', post_pk)

   return render(request, 'blog/detail.html', {'post':post})




def edit(request, post_pk):
   post = Post.objects.get(pk=post_pk)


   if request.method == 'POST':
       title = request.POST['title']
       content = request.POST['content']
       Post.objects.filter(pk=post_pk).update(
           title=title,
           content=content,
           author=request.user
       )
       return redirect('blog:detail', post_pk)


   return render(request, 'blog/edit.html', {'post':post})




def delete(request, post_pk):
   post = Post.objects.get(pk=post_pk)
   post.delete()
   return redirect('blog:home')


def delete_comment(request, post_pk, comment_pk):
   comment = Comment.objects.get(pk=comment_pk)
   comment.delete()
   return redirect('blog:detail', post_pk)

session13/project/accounts/templates/accounts/home.html
<div>
  <h1>블로그 회원관리</h1>
  <a href="{%url 'blog:home'%}">블로그로 가기</a>
</div>

session13/project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="UTF-8" />
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ceviche+One&family=Inter:wght@900&family=Jua&family=Koulen&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'blog/base.css' %}"
    />
    {% block css %} {% endblock css %}
    <title>Project</title>
  </head>

  <body>
    <nav id="navbar">
      <div class="navbar__logo">
        <a href="{% url 'blog:home' %}">NEXT-LIKELION</a>
      </div>
      <ul class="navbar__menu">
        <li class="navbar__menu__item">
          <a href="{% url 'blog:new' %}">뉴</a>
        </li>
        <li class="navbar__menu__item">
          <a href="{% url 'blog:home' %}">홈</a>
        </li>
        {% if user.is_authenticated %}
        <span class="navbar__menu__item">안녕, {{user.username}}</span>
        <li class="navbar__menu__item">
          <a href="{% url 'blog:logout'%}">로그아웃</a>
        </li>
        {% else %}
        <li class="navbar__menu__item">
          <a href="{% url 'blog:login'%}">로그인</a>
        </li>
        <li class="navbar__menu__item">
          <a href="{% url 'blog:signup'%}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </nav>
    <div class="title">{% block title %} {% endblock title %}</div>
    <div class="container">{% block content %} {% endblock content %}</div>
  </body>
</html>

session13/project/blog/templates/blog/detail.html
{% extends 'blog/base.html' %} {% block title %} Detail!{% endblock %} {% block
css%} {% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'blog/detail.css' %}" />
% endblock % {% block content %}
<div class="detail-post_container">
  <div class="detail_title">제목: {{post.title}}</div>
  <div class="detail_content">내용: {{post.content}}</div>
  <div class="detail-post_btn">
    <a href="{% url 'blog:home' %}">홈 화면</a>
    {% if user.is_authenticated and user.pk == post.author.pk %}
    <a href="{% url 'blog:edit' post.pk %}">수정하기</a>
    <a href="{% url 'blog:delete' post.pk %}">삭제하기</a>{% endif %}
  </div>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="text" name="content" />
    <button type="submit">댓글 작성</button>
  </form>
  {% for comment in post.comments.all %}
  <li>
    <span>{{comment.content}}</span>
    {% if user.pk == comment.author.pk and user.is_authenticated %}
    <a href="{% url 'blog:delete_comment' post.pk comment.pk %}">삭제</a>
    {% endif %}
  </li>
  {% endfor %}
</div>
{% endblock %}

session13/project/blog/templates/blog/edit.html
{% extends 'blog/base.html' %} {% block title %} Edit!{% endblock %} {% block
css %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/edit.css' %}" />
% endblock % {% block content %}
<div class="edit-post_container">
  <form method="POST" action="">
    {% csrf_token %}
    <input
      type="text"
      value="{{post.title}}"
      name="title"
      placeholder="수정할 제목!"
    />
    <textarea name="content" placeholder="수정할 내용!">
{{post.content}}</textarea
    >
    <input id="edit-post_btn" type="submit" value="수정하기" />
  </form>
</div>
{% endblock %}

session13/project/blog/templates/blog/home.html
{% extends 'blog/base.html' %} {% block title %} Home! {% endblock %} {% block
css %} {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/home.css' %}" />
% endblock % {% block content %}
<div class="posts_box">
  <a hre {% for post in posts %}f="{% url 'blog:detail' post.pk %}">
    <div class="post_wrapper">
      <div class="post_title">제목: {{post.title}}</div>
      <div class="post_content">내용 : {{post.content}}</div>
    </div>
  </a>
  {% endfor %}
</div>
<a id="post-button" href="{% url 'blog:new' %}">글 쓰러 가기!</a>
{% endblock %}

session13/project/blog/templates/blog/new.html
{% extends 'blog/base.html' %} % block css % {% load static %}
<meta charset="UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'blog/new.css' %}" />
% endblock % {% block title %} New! {% endblock %} {% block content %}
<div class="new-post_container">
  <form method="POST" action="">
    {% csrf_token %}
    <input type="text" placeholder="제목을 입력하세요!" name="title" />
    <textarea placeholder="내용을 입력하세요!" name="content"></textarea>
    <input id="new-post_btn" type="submit" value="작성하기" />
  </form>
</div>
{% endblock %}